import pandas as pd

# Function to rank and sort the candidates based on overall fit score generated by LLM
def rank_candidates(results, by="Overall Fit"):
    """Sort candidates by overall_fit score."""
    df = pd.DataFrame(results)
    df[by] = pd.to_numeric(df[by], errors="coerce")
    # Fill NaN with 0 so sorting works
    df = df.fillna({ "Similarity": 0, by: 0 })
    df = df.sort_values(by=by, ascending=False)
    return df
